#  Copyright 2021 Collate
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

FROM ubuntu:16.04

ENV JAVA_HOME=/usr
ENV HADOOP_HOME=/usr/local/hadoop-2.7.2
ENV HIVE_HOME=/usr/local/apache-hive-2.1.0-bin
ENV PATH=$PATH:$HADOOP_HOME/bin:$HIVE_HOME/bin

RUN apt-get update
RUN apt-get -y install ssh rsync curl openjdk-8-jre
RUN curl https://archive.apache.org/dist/hadoop/common/hadoop-2.7.2/hadoop-2.7.2.tar.gz | \
    tar -xz -C /usr/local/
RUN curl https://archive.apache.org/dist/hive/hive-2.1.0/apache-hive-2.1.0-bin.tar.gz | \
    tar -xz -C /usr/local/

RUN mkdir -p /user/hive/warehouse

RUN $HADOOP_HOME/bin/hadoop fs -chmod g+w /tmp
RUN $HADOOP_HOME/bin/hadoop fs -chmod g+w /user/hive/warehouse

RUN schematool -dbType derby -initSchema

EXPOSE 10000

CMD hiveserver2
